// Shared copy for the service, calculator, quote and assistant flows.
export const mnFlow = {
  webDevelopment: "Веб хөгжүүлэлт",
  modernFastAndReliableWebsitesAndWeb:
    "Орчин үеийн, хурдан ба найдвартай вебсайт болон веб систем. Дизайнаас deploy хүртэл нэг багаар.",
  responsiveDesign: "Responsive дизайн",
  seoOptimization: "SEO оновчилгоо",
  cmsSystem: "CMS систем",
  eCommercePlatform: "E-commerce платформ",
  technologies: "Технологиуд",
  twoToEightWeeks: "2–8 долоо хоног",
  from500000: "₮500,000-с",
  mobileDevelopment: "Мобайл хөгжүүлэлт",
  iosAndAndroidAppsWithANative:
    "iOS болон Android платформын аппликейшн. Native-тэй эн зэрэгцэх UX, дэлгүүрт нийтлэх хүртэл дагалдана.",
  nativeDevelopment: "Native хөгжүүлэлт",
  uiUxDesign: "UI/UX дизайн",
  appStoreApproval: "App Store зөвшөөрөл",
  fourToTwelveWeeks: "4–12 долоо хоног",
  from800000: "₮800,000-с",
  erpCustomModules: "ERP · Custom модуль",
  odooErpSystem: "Odoo ERP систем",
  anIntegratedBusinessManagementSystemAdaptedTo:
    "Бизнес удирдлагын цогц систем. Монгол стандартад нийцүүлсэн хэрэгжүүлэлт, шаардлагатай газарт нь custom модуль.",
  financialManagement: "Санхүү удирдлага",
  inventoryManagement: "Бараа материалын удирдлага",
  crmSystem: "CRM систем",
  humanResourcesManagement: "Хүний нөөцийн удирдлага",
  modules: "Модулууд",
  sales: "Борлуулалт",
  purchasing: "Худалдан авалт",
  warehouse: "Агуулах",
  humanResources: "Хүний нөөц",
  sixToSixteenWeeks: "6–16 долоо хоног",
  from1200000: "₮1,200,000-с",
  discovery: "Хэрэгцээний судалгаа",
  weStudyYourBusinessNeedsAndDefine:
    "Таны бизнесийн хэрэгцээг сайтар судалж, шаардлагыг тодорхойлно",
  planning: "Төлөвлөлт",
  weDesignTheTechnicalSolutionVisualsAnd:
    "Техникийн шийдэл, дизайн болон хуваарийг боловсруулна",
  design: "Дизайн",
  weCreateUiUxDesignsTailoredTo:
    "UI/UX дизайныг таны брэндэд тохируулан бэлтгэнэ",
  development: "Хөгжүүлэлт",
  weBuildYourSystemUsingModernTechnologies:
    "Орчин үеийн технологи ашиглан системийг хөгжүүлнэ",
  testing: "Туршилт",
  weThoroughlyTestEveryFeatureOfThe:
    "Системийн бүх функцийг нарийвчлан шалгаж туршина",
  launch: "Ашиглалтад оруулах",
  weLaunchTheSystemAndProvideOngoing:
    "Системийг амжилттай ашиглалтад оруулж дэмжлэг үзүүлнэ",
  projectsLaunched: "Launch хийсэн төсөл",
  fullTimeDevelopers: "Full-time хөгжүүлэгч",
  yearsOfExperience: "Жилийн туршлага",
  supportService: "Дэмжлэгийн үйлчилгээ",
  home: "Нүүр хуудас",
  fromIdeaToProduction: "Санаанаас production хүртэл",
  digitalServicesForYourBusinessWithClear:
    "Танай бизнесийн дижитал шийдлийг бүрэн хангах үйлчилгээнүүд — хугацаа, багц, эхлэх үнэ нь тодорхой.",
  timeline: "Хугацаа",
  startingPrice: "Эхлэх үнэ",
  getAnEstimate: "Тооцоо гаргах",
  howWeWork: "Бидний ажлын үйл явц",
  sixStepsToDeliverYourProjectEach:
    "Таны төслийг амжилттай хэрэгжүүлэх 6 алхам. Алхам бүрийн төгсгөлд харагдах үр дүн гарна.",
  whyChooseUs: "Яагаад биднийг сонгох ёстой?",
  aTeamThatDeliversWorkingSystemsQuickly:
    "Богино хугацаанд ажилладаг систем хүлээлгэж өгөх, дараа нь түүнийг нь тогтвортой ажиллуулах хоёрыг зэрэг хийдэг баг.",
  letSTalkAboutYourProject: "Танай төслийн талаар ярилцъя",
  inOurFirstMeetingWeWillClarify:
    "Хэрэгцээндээ тохирсон шийдэл, ойролцоо төсөв, хугацааг эхний уулзалтаар тодруулна.",
  getAFreeConsultation: "Үнэгүй зөвлөгөө авах",
  viewPortfolio: "Портфолио үзэх",
  website: "Вэб сайт",
  companySitesLandingPagesPortals: "Танилцуулга, лендинг, портал",
  mobileApp: "Мобайл апп",
  implementationConfigurationModules: "Нэвтрүүлэлт, тохиргоо, модуль",
  customSolution: "Захиалгат шийдэл",
  internalSystemsIntegrations: "Дотоод систем, интеграци",
  simple: "Энгийн",
  templatesAFewScreens: "Бэлэн загвар, цөөн дэлгэц",
  medium: "Дундаж",
  customDesignAndBusinessLogic: "Захиалгат дизайн, логик",
  complex: "Төвөгтэй",
  multipleRolesDeepIntegrations: "Олон дүр, гүн интеграци",
  enterprise: "Энтерпрайз",
  scaleAuditSla: "Ачаалал, аудит, SLA",
  contentManagementCms: "Контент удирдлага (CMS)",
  eCommerce: "Цахим худалдаа",
  apiIntegration: "API интеграци",
  userAccessManagement: "Хэрэглэгчийн эрхийн систем",
  adminPanel: "Админ панел",
  multilingualSupport: "Олон хэлний дэмжлэг",
  analyticsAndReporting: "Аналитик, тайлан",
  urgent: "Яаралтай",
  oneToTwoWeeks: "1–2 долоо хоног",
  standard: "Стандарт",
  twoToFourWeeks: "2–4 долоо хоног",
  flexible: "Уян хатан",
  fourToEightWeeks: "4–8 долоо хоног",
  longTerm: "Урт хугацаа",
  eightPlusWeeks: "8+ долоо хоног",
  onePerson: "1 хүн",
  twoToThreePeople: "2–3 хүн",
  fourToSixPeople: "4–6 хүн",
  sixPlusPeople: "6+ хүн",
  required: "заавал",
  optional: "сонголт",
  projectType: "төслийн төрөл",
  complexity: "төвөгтэй байдал",
  description: "тайлбар",
  valueBase: "{0} · суурь",
  valueHours: "{0} цаг",
  valueHours100: "+{0} цаг",
  projectCostCalculator: "Төслийн үнийн тооцоолуур",
  fillInThreeFieldsForAnEstimate:
    "Гурван талбар бөглөхөд л ойролцоо тооцоо гарна. Тооцоо нь",
  perPersonHour: "/хүн-цаг тарифаар бодогдоно.",
  projectTypeLabel: "Төслийн төрөл",
  valueValueHours: "{0} · {1} цаг",
  complexity106: "Төвөгтэй байдал",
  additionalFeatures: "Нэмэлт функцууд",
  h: "ц",
  preferredTimeline: "Хүссэн хугацаа",
  teamSize: "Багийн хэмжээ",
  projectDescription: "Төслийн тайлбар",
  whatProblemAreYouSolvingWhoWill:
    "Юу шийдэх гэж байгаа, хэн ашиглах, аль системүүдтэй холбогдох вэ?",
  pleaseEnterAtLeastValueCharactersCurrently:
    "Дор хаяж {0} тэмдэгт бичнэ үү — одоо {1}.",
  valueValueCharacters: "{0}/{1} тэмдэгт",
  preliminaryEstimate: "Урьдчилсан тооцоо",
  personHours: "Хүн-цаг",
  weeks: "7 хоног",
  hours: "цаг ×",
  selectAProjectTypeAndComplexityTo:
    "Төслийн төрөл, төвөгтэй байдлыг сонгонгуут тооцоо энд гарч ирнэ.",
  thisIsAnIndicativeEstimateTheFinal:
    "Энэ бол чиг баримжаа авах тооцоо. Эцсийн үнэ шаардлага тодорхойлсны дараа гэрээнд тусна.",
  requestAQuote: "Үнийн санал авах",
  missing: "Дутуу байна:",
  continue: "Үргэлжлүүлэх",
  websiteDevelopment: "Вэб сайт хөгжүүлэлт",
  mobileAppDevelopment: "Мобайл апп хөгжүүлэлт",
  over5000000: "₮5,000,000-с дээш",
  letSDiscuss: "Ярилцаж тохирно",
  urgent12Weeks: "Яаралтай (1–2 долоо хоног)",
  standard24Weeks: "Стандарт (2–4 долоо хоног)",
  flexible48Weeks: "Уян хатан (4–8 долоо хоног)",
  longTerm8Weeks: "Урт хугацаа (8+ долоо хоног)",
  pleaseEnterYourName: "Нэрээ бичнэ үү.",
  pleaseEnterAValidEmailAddress: "Хүчинтэй имэйл хаяг оруулна уу.",
  pleaseEnterYourPhoneNumber: "Холбогдох утасны дугаараа оруулна уу.",
  pleaseSelectAProjectType: "Төслийн төрлөө сонгоно уу.",
  pleaseDescribeYourProjectInAtLeast:
    "Төслөө дор хаяж {0} тэмдэгтээр тайлбарлана уу.",
  theAnswerDoesNotMatch: "Хариу таарахгүй байна.",
  requestReceived: "Хүсэлт хүлээн авлаа",
  weWillSendADetailedQuoteWithin: "Бид 24 цагийн дотор",
  text: "хаяг руу дэлгэрэнгүй үнийн санал илгээнэ.",
  requestReference: "Хүсэлтийн дугаар",
  copied: "Хуулсан",
  copy: "Хуулах",
  backToHome: "Нүүр хуудас руу",
  startANewRequest: "Шинэ хүсэлт үүсгэх",
  backToCalculator: "Тооцоолуур руу буцах",
  quotePageTitle: "Үнийн санал хүсэх",
  theMoreDetailYouShareTheMore:
    "Дэлгэрэнгүй бичих тусам үнийн санал нь бодит болно. Бид 24 цагийн дотор хариу өгнө.",
  fromTheCalculator: "Тооцоолуураас",
  personHoursLowercase: "хүн-цаг",
  editEstimate: "Тооцоог засах",
  fullName: "Овог нэр",
  alexSmith: "Батболд Ганбат",
  emailAddress: "Имэйл хаяг",
  phoneNumber: "Утасны дугаар",
  companyName: "Компанийн нэр",
  optionalParenthetical: "(сонголт)",
  companyLtd: "Компани ХХК",
  selectAProjectType: "Төслийн төрлийг сонгоно уу",
  detailedProjectDescription: "Төслийн дэлгэрэнгүй тайлбар",
  characters: "тэмдэгт",
  budget: "Төсөв",
  budgetRange: "Төсвийн хэмжээ",
  humanVerification: "Робот эсэхийг шалгах",
  answer: "Хариу",
  getAnotherQuestion: "Өөр асуулт авах",
  sending: "Илгээж байна…",
  sendRequest: "Хүсэлт илгээх",
  back: "Буцах",
  other: "Бусад",
  requestADetailedQuote: "Дэлгэрэнгүй үнийн санал авах",
  estimateAnotherProject: "Өөр төсөл тооцуулах",
  helloIMTheProvisionMnAssistant:
    "Сайн байна уу! Би Provision.mn-ийн туслах байна. Төслийнхөө талаар хэдэн зүйл асуугаад урьдчилсан тооцоо гаргаж өгье. Та ямар төрлийн төсөл хийх гэж байна?",
  simpleCompanyWebsite: "Энгийн танилцуулах сайт",
  eCommerceStore: "E-commerce дэлгүүр",
  blogOrNewsSite: "Блог, мэдээний сайт",
  customFeatures: "Захиалгат функц",
  iosApp: "iOS апп",
  androidApp: "Android апп",
  inventory: "Нярав",
  finance: "Санхүү",
  all: "Бүгд",
  soloFreelancer: "1 хүн (фрийлансер)",
  smallTeam: "2-3 хүн (жижиг баг)",
  mediumTeam: "4-6 хүн (дундаж баг)",
  largeTeam: "6+ хүн (том баг)",
  valueUnderstoodWhichFeaturesDoYouNeed:
    "{0} — ойлголоо. Ямар функцууд хэрэгтэй вэ? Товчоор бичээд ч болно.",
  thankYouWhatTeamSizeDoYou:
    "Баярлалаа. Хэр хэмжээний баг хэрэгтэй гэж бодож байна?",
  estimateHeading: "Урьдчилсан тооцоо:",
  typeValue: "• Төрөл — {0}",
  timelineAboutValueWeeks: "• Хугацаа — ойролцоогоор {0} долоо хоног",
  teamValue: "• Баг — {0}",
  priceValue: "• Үнэ — ₮{0}",
  thisIsAnIndicativeEstimateWouldYou:
    "Энэ бол чиг баримжаа авах тооцоо. Албан ёсны санал авах уу?",
  chooseADetailedQuoteOrStartAnother:
    "Дэлгэрэнгүй санал авах эсвэл дахин тооцоолохыг сонгоно уу.",
  chatWithTheAssistant: "Туслахтай ярих",
  provisionAssistant: "Provision туслах",
  close: "Хаах",
  typing: "Бичиж байна…",
  writeAMessage: "Мессеж бичих…",
  message: "Мессеж",
  send: "Илгээх",
};
export const enFlow = {
  webDevelopment: "Web development",
  modernFastAndReliableWebsitesAndWeb:
    "Modern, fast and reliable websites and web applications. One team, from design to deployment.",
  responsiveDesign: "Responsive design",
  seoOptimization: "SEO optimization",
  cmsSystem: "CMS system",
  eCommercePlatform: "E-commerce platform",
  technologies: "Technologies",
  twoToEightWeeks: "2–8 weeks",
  from500000: "From ₮500,000",
  mobileDevelopment: "Mobile development",
  iosAndAndroidAppsWithANative:
    "iOS and Android apps with a native-quality experience, supported all the way through store publication.",
  nativeDevelopment: "Native development",
  uiUxDesign: "UI/UX design",
  appStoreApproval: "App Store approval",
  fourToTwelveWeeks: "4–12 weeks",
  from800000: "From ₮800,000",
  erpCustomModules: "ERP · Custom modules",
  odooErpSystem: "Odoo ERP system",
  anIntegratedBusinessManagementSystemAdaptedTo:
    "An integrated business management system, adapted to Mongolian requirements with custom modules where needed.",
  financialManagement: "Financial management",
  inventoryManagement: "Inventory management",
  crmSystem: "CRM system",
  humanResourcesManagement: "Human resources management",
  modules: "Modules",
  sales: "Sales",
  purchasing: "Purchasing",
  warehouse: "Warehouse",
  humanResources: "Human resources",
  sixToSixteenWeeks: "6–16 weeks",
  from1200000: "From ₮1,200,000",
  discovery: "Discovery",
  weStudyYourBusinessNeedsAndDefine:
    "We study your business needs and define the requirements",
  planning: "Planning",
  weDesignTheTechnicalSolutionVisualsAnd:
    "We design the technical solution, visuals and delivery schedule",
  design: "Design",
  weCreateUiUxDesignsTailoredTo:
    "We create UI/UX designs tailored to your brand",
  development: "Development",
  weBuildYourSystemUsingModernTechnologies:
    "We build your system using modern technologies",
  testing: "Testing",
  weThoroughlyTestEveryFeatureOfThe:
    "We thoroughly test every feature of the system",
  launch: "Launch",
  weLaunchTheSystemAndProvideOngoing:
    "We launch the system and provide ongoing support",
  projectsLaunched: "Projects launched",
  fullTimeDevelopers: "Full-time developers",
  yearsOfExperience: "Years of experience",
  supportService: "Support service",
  home: "Home",
  fromIdeaToProduction: "From idea to production",
  digitalServicesForYourBusinessWithClear:
    "Digital services for your business, with clear timelines, packages and starting prices.",
  timeline: "Timeline",
  startingPrice: "Starting price",
  getAnEstimate: "Get an estimate",
  howWeWork: "How we work",
  sixStepsToDeliverYourProjectEach:
    "Six steps to deliver your project, each ending with a tangible result.",
  whyChooseUs: "Why choose us?",
  aTeamThatDeliversWorkingSystemsQuickly:
    "A team that delivers working systems quickly and keeps them running reliably.",
  letSTalkAboutYourProject: "Let’s talk about your project",
  inOurFirstMeetingWeWillClarify:
    "In our first meeting, we will clarify the solution, estimated budget and timeline that fit your needs.",
  getAFreeConsultation: "Get a free consultation",
  viewPortfolio: "View portfolio",
  website: "Website",
  companySitesLandingPagesPortals: "Company sites, landing pages, portals",
  mobileApp: "Mobile app",
  implementationConfigurationModules: "Implementation, configuration, modules",
  customSolution: "Custom solution",
  internalSystemsIntegrations: "Internal systems, integrations",
  simple: "Simple",
  templatesAFewScreens: "Templates, a few screens",
  medium: "Medium",
  customDesignAndBusinessLogic: "Custom design and business logic",
  complex: "Complex",
  multipleRolesDeepIntegrations: "Multiple roles, deep integrations",
  enterprise: "Enterprise",
  scaleAuditSla: "Scale, audit, SLA",
  contentManagementCms: "Content management (CMS)",
  eCommerce: "E-commerce",
  apiIntegration: "API integration",
  userAccessManagement: "User access management",
  adminPanel: "Admin panel",
  multilingualSupport: "Multilingual support",
  analyticsAndReporting: "Analytics and reporting",
  urgent: "Urgent",
  oneToTwoWeeks: "1–2 weeks",
  standard: "Standard",
  twoToFourWeeks: "2–4 weeks",
  flexible: "Flexible",
  fourToEightWeeks: "4–8 weeks",
  longTerm: "Long-term",
  eightPlusWeeks: "8+ weeks",
  onePerson: "1 person",
  twoToThreePeople: "2–3 people",
  fourToSixPeople: "4–6 people",
  sixPlusPeople: "6+ people",
  required: "required",
  optional: "optional",
  projectType: "project type",
  complexity: "complexity",
  description: "description",
  valueBase: "{0} · base",
  valueHours: "{0} hours",
  valueHours100: "+{0} hours",
  projectCostCalculator: "Project cost calculator",
  fillInThreeFieldsForAnEstimate:
    "Fill in three fields for an estimate. Calculated at",
  perPersonHour: "per person-hour.",
  projectTypeLabel: "Project type",
  valueValueHours: "{0} · {1} hours",
  complexity106: "Complexity",
  additionalFeatures: "Additional features",
  h: "h",
  preferredTimeline: "Preferred timeline",
  teamSize: "Team size",
  projectDescription: "Project description",
  whatProblemAreYouSolvingWhoWill:
    "What problem are you solving, who will use it, and which systems should it connect to?",
  pleaseEnterAtLeastValueCharactersCurrently:
    "Please enter at least {0} characters — currently {1}.",
  valueValueCharacters: "{0}/{1} characters",
  preliminaryEstimate: "Preliminary estimate",
  personHours: "Person-hours",
  weeks: "weeks",
  hours: "hours ×",
  selectAProjectTypeAndComplexityTo:
    "Select a project type and complexity to see your estimate here.",
  thisIsAnIndicativeEstimateTheFinal:
    "This is an indicative estimate. The final price will be agreed in the contract after requirements are defined.",
  requestAQuote: "Request a quote",
  missing: "Missing:",
  continue: "Continue",
  websiteDevelopment: "Website development",
  mobileAppDevelopment: "Mobile app development",
  over5000000: "Over ₮5,000,000",
  letSDiscuss: "Let’s discuss",
  urgent12Weeks: "Urgent (1–2 weeks)",
  standard24Weeks: "Standard (2–4 weeks)",
  flexible48Weeks: "Flexible (4–8 weeks)",
  longTerm8Weeks: "Long-term (8+ weeks)",
  pleaseEnterYourName: "Please enter your name.",
  pleaseEnterAValidEmailAddress: "Please enter a valid email address.",
  pleaseEnterYourPhoneNumber: "Please enter your phone number.",
  pleaseSelectAProjectType: "Please select a project type.",
  pleaseDescribeYourProjectInAtLeast:
    "Please describe your project in at least {0} characters.",
  theAnswerDoesNotMatch: "The answer does not match.",
  requestReceived: "Request received",
  weWillSendADetailedQuoteWithin:
    "We will send a detailed quote within 24 hours to",
  text: ".",
  requestReference: "Request reference",
  copied: "Copied",
  copy: "Copy",
  backToHome: "Back to home",
  startANewRequest: "Start a new request",
  backToCalculator: "Back to calculator",
  quotePageTitle: "Request a quote",
  theMoreDetailYouShareTheMore:
    "The more detail you share, the more accurate the quote. We will respond within 24 hours.",
  fromTheCalculator: "From the calculator",
  personHoursLowercase: "person-hours",
  editEstimate: "Edit estimate",
  fullName: "Full name",
  alexSmith: "Alex Smith",
  emailAddress: "Email address",
  phoneNumber: "Phone number",
  companyName: "Company name",
  optionalParenthetical: "(optional)",
  companyLtd: "Company Ltd",
  selectAProjectType: "Select a project type",
  detailedProjectDescription: "Detailed project description",
  characters: "characters",
  budget: "Budget",
  budgetRange: "Budget range",
  humanVerification: "Human verification",
  answer: "Answer",
  getAnotherQuestion: "Get another question",
  sending: "Sending…",
  sendRequest: "Send request",
  back: "Back",
  other: "Other",
  requestADetailedQuote: "Request a detailed quote",
  estimateAnotherProject: "Estimate another project",
  helloIMTheProvisionMnAssistant:
    "Hello! I’m the Provision.mn assistant. I’ll ask a few questions about your project and give you an initial estimate. What kind of project are you planning?",
  simpleCompanyWebsite: "Simple company website",
  eCommerceStore: "E-commerce store",
  blogOrNewsSite: "Blog or news site",
  customFeatures: "Custom features",
  iosApp: "iOS app",
  androidApp: "Android app",
  inventory: "Inventory",
  finance: "Finance",
  all: "All",
  soloFreelancer: "1 person (freelancer)",
  smallTeam: "2-3 people (small team)",
  mediumTeam: "4-6 people (medium team)",
  largeTeam: "6+ people (large team)",
  valueUnderstoodWhichFeaturesDoYouNeed:
    "{0} — understood. Which features do you need? A short description is fine too.",
  thankYouWhatTeamSizeDoYou: "Thank you. What team size do you have in mind?",
  estimateHeading: "Preliminary estimate:",
  typeValue: "• Type — {0}",
  timelineAboutValueWeeks: "• Timeline — about {0} weeks",
  teamValue: "• Team — {0}",
  priceValue: "• Price — ₮{0}",
  thisIsAnIndicativeEstimateWouldYou:
    "This is an indicative estimate. Would you like a formal quote?",
  chooseADetailedQuoteOrStartAnother:
    "Choose a detailed quote or start another estimate.",
  chatWithTheAssistant: "Chat with the assistant",
  provisionAssistant: "Provision assistant",
  close: "Close",
  typing: "Typing…",
  writeAMessage: "Write a message…",
  message: "Message",
  send: "Send",
} satisfies typeof mnFlow;

export type FlowCopy = typeof mnFlow;

export function formatCopy(
  template: string,
  ...values: (string | number | undefined)[]
) {
  return template.replace(/\{(\d+)\}/g, (_, index: string) =>
    String(values[Number(index)] ?? ""),
  );
}
